### PR TITLE
Updating Сomparison API version and related code changes.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-MVC/pull/30.

### CODE REVIEW

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
- src/Products/Comparison/Controllers/ComparisonApiController.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798436&bid=18978931)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 10
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Controllers/ComparisonApiController.cs  1
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798437&bid=18978932)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798436&bid=18978931)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798437&bid=18978932)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 6
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798436&bid=18978931)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
           

Complexity increasing per file
==============================
- src/Products/Comparison/Service/ComparisonServiceImpl.cs  2
         

Clones added
============
- src/Products/Comparison/Config/ComparisonConfiguration.cs  1
         

Clones removed
==============
+ src/Products/Comparison/Service/ComparisonServiceImpl.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5798437&bid=18978932)

**Review by Pavel-Teplitsky — APPROVED** [review]

**Pull request merged**
