### PR TITLE
Added default folder for license and documents

### PR DESCRIPTION
**Pull request by Pavel-Teplitsky**

### CODE REVIEW

**Comment by Pavel-Teplitsky** [comment]
I was not able to found out any information about licensing for it, also you can found this file via this [link ](http://aaaf.org.uk/wp-content/uploads/2016/01/Color-Theory-For-Startups.pdf) and since that I can assume that this file can be distributed. Any way to be sure for 100% I can remove remove it from the repository.

**Comment by Pavel-Teplitsky** [comment]
The pdf document [link](http://aaaf.org.uk/wp-content/uploads/2016/01/Color-Theory-For-Startups.pdf)

**Comment by egorovpavel** [comment]
Yes, remove them please. It will be better if we distribute our own documents.

**Comment by Pavel-Teplitsky** [comment]
> Yes, remove them please. It will be better if we distribute our own documents.

Done

**Pull request merged**
