### PR TITLE
Increase displayed metadata properties, API version update.

### PR DESCRIPTION
**Pull request by kegor**
Replicated changes from groupdocs-metadata/GroupDocs.Metadata-for-.NET-MVC#3.

### CODE REVIEW

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -4
         

Clones removed
==============
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5997353&bid=19664137)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -4
         

Clones removed
==============
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5997354&bid=19664138)

**Comment by bobkovalex** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -4
         

Clones removed
==============
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/groupdocs-total/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5997353&bid=19664137)

**Comment by egorovpavel** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -4
         

Clones removed
==============
+ src/Products/Metadata/Controllers/MetadataApiController.cs  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GroupDocs/GroupDocs.Total-for-NET-MVC/pullRequest?prid=5997354&bid=19664138)

**Pull request merged**
